#!/bin/sh
# Give a battery name (e.g. BAT0) as an argument.

if [ -f "/sys/class/power_supply/BAT0/capacity" ]; then
  capacity="$(cat /sys/class/power_supply/BAT0/capacity)"
  status="$(cat /sys/class/power_supply/BAT0/status)"
elif [ -f "/sys/class/power_supply/BAT1/capacity" ]; then
  capacity="$(cat /sys/class/power_supply/BAT1/capacity)"
  status="$(cat /sys/class/power_supply/BAT1/status)"
else
  exit 1
fi

case $BLOCK_BUTTON in
3) notifications "🔋 Battery module" "🔋: discharging
🛑: not charging
♻: stagnant charge
🔌: charging
⚡: charged
❗: battery very low!
- Text color reflects charge left" ;;
esac

if [ "$capacity" -ge 75 ]; then
  color="#00ff00"
elif [ "$capacity" -ge 50 ]; then
  color="#ffffff"
elif [ "$capacity" -ge 25 ]; then
  color="#ffff00"
else
  color="#ff0000"
  warn="❗"
fi

[ -z $warn ] && warn=" "

[ "$status" = "Charging" ] && color="#ffffff"

printf "<span color='%s'>%s%s%s</span>\n" "$color" "$(echo "$status" | sed -e "s/,//;s/Discharging/🔋/;s/Not charging/🛑/;s/Charging/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
