#!/bin/sh

echo " $(date "+%b %d, %Y %H:%M")"

case $BLOCK_BUTTON in
1) notifications "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notifications "Appointments" "$(calcurse -D ~/.config/calcurse -d3)" ;;
2) myterminal -e calcurse -D ~/.config/calcurse ;;
3) notifications "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
esac
