#!/usr/bin/env bash

cmd_exists check-for-updates && exit

case $BLOCK_BUTTON in
1) setsid -f check-for-updates --ask ;;
2) notifications "$(check-for-updates)" ;;
3) notifications "🎁 Upgrade module" "📦: number of upgradable packages
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

check-for-updates | sed "s/^/📦/;s/^📦0$//g"
