#!/bin/sh

case $BLOCK_BUTTON in
1) setsid myterminal -e alsamixer & ;;
2) amixer sset Master toggle ;;
4) amixer sset Master 1%+ >/dev/null 2>/dev/null ;;
5) amixer sset Master 1%- >/dev/null 2>/dev/null ;;
3) notifications "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
esac

volstat="$(amixer get Master)"

echo "$volstat" | grep "\[off\]" >/dev/null && printf "🔇\\n" && exit

vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed 's/[^0-9]*//g' | sed 's|%||' | head -n1)

if [[ $vol -gt 70 ]]; then
  icon="🔊"
elif [[ $vol -lt 30 ]]; then
  icon="🔈"
else
  icon="🔉"
fi

printf "%s %s%%\\n" "$icon" "$vol"
