#!/bin/sh

location="${MYLOCATION_ID:-$1}"
[ -z "$location" ] || { location="$location+" && rm -f "$HOME/.cache/weatherreport"; }

getforecast() {
  am_i_online || return 1
  curl -s "wttr.in/$location?Af" >"$HOME/.cache/weatherreport" || return 1
}

showweather() {
  printf "%s" "$(sed '16q;d' "$HOME/.cache/weatherreport" | grep -wo "[0-9]*%" | sort -n | sed -e '$!d' | sed -e "s/^/☔ /g" | tr -d '\n')"
  sed '13q;d' "$HOME/.cache/weatherreport" | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " ❄️",$1 "°","🌞",$2 "°"}'
}

case $BLOCK_BUTTON in
1) myterminal -e less -S "$HOME/.cache/weatherreport" ;;
2) getforecast && showweather ;;
3) notifications "🌈 Weather module" "\- Left click for full forecast.
- Middle click to update forecast.
☔: Chance of rain/snow
❄: Daily low
🌞: Daily high" ;;
esac

if [ "$(stat -c %y "$HOME/.cache/weatherreport" >/dev/null 2>&1 | awk '{print $1}')" != "$(date '+%Y-%m-%d')" ]; then
  getforecast && showweather
else
  showweather
fi
