# For more information about the configurations used
# in this file, please see the Travis CI documentation.
# .travis.yml
# https://docs.travis-ci.com

sudo: enabled

install:
  - sudo bash -c "$(curl -LSs https://github.com/desktopmgr/installer/raw/main/install.sh)"
  - sudo pkmgr init
  - pkmgr update
  - sudo dotfiles admin scripts
  - dotfiles install i3
  - bash -c "[ -f $(command -v i3 >/dev/null 2>&1) ] && timeout --signal=9 --foreground --preserve-status 5 i3 || true"

matrix:
  include:
    - os: linux
      dist: bionic
      language: bash
      sudo: enabled

notifications:
  email:
    on_failure: never
    on_success: never
